export const Errors = {
  CALLER_IS_NOT_OWNER: 200,
  INVALID_NEW_OWNER: 201,
  INVALID_GAS_RECIPIENT: 202,
  CONTRACT_IS_NOT_ACTIVE: 203,
  INVALID_CODE: 204,
  PLATFORM_CODE_ALREADY_SET: 205,
  INVALID_ADDRESS: 206,
  CALLER_IS_NOT_UPGRADER: 207,
  CALLER_IS_NOT_INSTANCE: 208,
  INVALID_DEPLOY_PARAMS: 209,
};
